apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # API 服務器的 TLS 證書和私鑰（必填）。
  # 當金鑰缺失或無效時，使用自簽名證書自動生成。
  tls.crt:
  tls.key:

  # 管理員密碼的 bcrypt 雜湊及其最後修改時間（必填）。
  # 缺失時自動生成為 argocd-server pod 的名稱。
  admin.password:
  admin.passwordMtime:

  # 用於會話驗證的隨機服務器簽名金鑰（必填）。
  # 缺失時自動生成。
  server.secretkey:

  # 用於驗證 GitHub、GitLab、BitBucket webhook 事件的共享密鑰（可選）。
  # 請參閱 https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/webhook.md 以獲取更多詳細信息。
  # github webhook 密鑰
  webhook.github.secret: shhhh! it's a github secret
  # gitlab webhook 密鑰
  webhook.gitlab.secret: shhhh! it's a gitlab secret
  # bitbucket webhook 密鑰
  webhook.bitbucket.uuid: your-bitbucket-uuid
  # bitbucket server webhook 密鑰
  webhook.bitbucketserver.secret: shhhh! it's a bitbucket server secret
  # gogs server webhook 密鑰
  webhook.gogs.secret: shhhh! it's a gogs server secret
  # azure devops webhook 使用者名稱
  webhook.azuredevops.username: shhhh! it's an azure devops secret
  # azure devops webhook 密碼
  webhook.azuredevops.password: shhhh! it's an azure devops secret

  # 額外的使用者密碼及其最後修改時間（請參閱 argocd-cm.yaml 中的使用者定義）
  accounts.alice.password:
  accounts.alice.passwordMtime:
  # 生成的帳戶權杖/api 金鑰列表
  accounts.alice.tokens: |
    [{"id":"123","iat":1583789194,"exp":1583789194}]
